services:
  easy-work-db:
    container_name: container-easy-work-db
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network-easy-work

  easy-work-api:
    container_name: container-easy-work-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - easy-work-data:/usr/src/app/easy-work-api
    build:
      context: ./
    ports:
      - "3000:3000"
    networks:
      - network-easy-work

volumes:
  postgres_data: { driver: local }
  easy-work-data: { driver: local }
networks:
  network-easy-work: {}
