version: "3.8"
services:
  easy-work-api:
    container_name: container-easy-work-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    build:
      context: ./
    ports:
      - "3000:3000"
